name: Code Format & API Docs

on:
  workflow_dispatch:  # Activate this workflow manually
  # Activate this workflow at every push of code changes
  # Note: using push instead of pull_request make the actions
  # run on the contributor's actions instead of Haystack's.
  # This is necessary for permission issues: Haystack's CI runners 
  # cannot push changes back to the source fork.
  # TODO make sure this is still necessary later on.
  push:
    branches-ignore:
      - 'master'
    paths:
      - '**/*.py'
      - '**/*.yml'
      - '**/*.ipynb'
      - '**/setup.cfg'
      - '**/pyproject.toml'

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .[all]
          pip install rest_api/
          pip install ui/
          
      - name: Code and Docs Updates
        run: ./.github/utils/code_and_docs.sh
      
      - name: Commit files
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update Documentation & Code Style" -a || echo "No changes to commit"
          git push
