name: Checklist

on:
  workflow_dispatch:
  pull_request:


jobs:

  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v6
      env:
        COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        ISSUE_NUMBER: ${{ github.event.number }}
      with:
        script: |
          const script = require('./.github/utils/checklist.js')
          await script({github, context, core})