name: Lint

on:
  workflow_dispatch:  # Activate this workflow manually
  pull_request:
    paths:
      - '**/*.py'
      - '**/setup.cfg'
      - '**/pyproject.toml'

jobs:

  mypy:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # Mypy can't run properly on 3.7 as it misses support for Literal types.
        # FIXME once we drop support for 3.7, use the cache.
        python-version: 3.8

    - name: Install dependencies
      run: |
        # FIXME installing the packages before running mypy raises
        # a lot of errors which were never detected before!
        # pip install .
        # pip install rest_api/
        # pip install ui/

        # FIXME --install-types does not work properly yet, see https://github.com/python/mypy/issues/10600
        # Hotfixing by installing type packages explicitly. 
        # Run mypy --install-types haystack locally to ensure the list is still up to date
        # mypy --install-types --non-interactive .

        pip install mypy pydantic types-Markdown types-PyYAML types-requests types-setuptools types-six types-tabulate types-chardet types-emoji types-protobuf

    - name: Mypy
      run: |
        echo "=== haystack/ ==="
        mypy haystack

        echo "=== rest_api/ ==="
        mypy rest_api --exclude=rest_api/build/ --exclude=rest_api/test/

        echo "=== ui/ ==="
        mypy ui --exclude=ui/build/ --exclude=ui/test/


  pylint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Haystack
      run: |
        pip install --upgrade pip
        pip install .[all]
        pip install rest_api/
        pip install ui/

    - name: Pylint
      run: |
        pylint -ry haystack/
        pylint -ry rest_api/
        pylint -ry ui/
