name: Tests (Linux)

on:
  # Activate this workflow manually
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - '**/*.yml'
      - '**/*.ipynb'
      - '**/setup.cfg'
      - '**/pyproject.toml'
      - ".github/**/*.*"

jobs:

  unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false  # Avoid cancelling the others if one of these fails
      matrix: 
        folder:
          - "node_tests"
          - "pipeline_tests"
          - "modeling_tests"
          - "other_tests"
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .

    - name: Run tests
      id: pytest
      env:
        TOKENIZERS_PARALLELISM: 'false'  # Avoid logspam by tokenizers
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "not elasticsearch and not faiss and not milvus and not milvus1 and not weaviate and not pinecone and not graphdb and not integration" test/${{ matrix.folder }} --document_store_type=memory,sql)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=${{ matrix.folder }}_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: |
        ${{ steps.pytest.outputs.node_tests_run }} +
        ${{ steps.pytest.outputs.pipelines_tests_run }} +
        ${{ steps.pytest.outputs.modeling_tests_run }} +
        ${{ steps.pytest.outputs.other_tests_run }}


  elasticsearch-tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Setup Elasticsearch
      run: |
        docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2
        docker run -d -p 9201:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:1.2.4

      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "elasticsearch and not integration" test/document_store_tests/ --document_store_type=elasticsearch)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}


  faiss-tests:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'faiss')

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .[faiss]

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "faiss and not integration" test/document_store_tests/ --document_store_type=faiss)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}
  

  milvus-tests:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'milvus')

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Setup Milvus
      run: |
        cd ../../   # Avoid causing permission issues on hashFiles later by creating unreadable folders like "volumes"
        wget https://github.com/milvus-io/milvus/releases/download/v2.0.0/milvus-standalone-docker-compose.yml -O docker-compose.yml
        sudo docker-compose up -d
        sudo docker-compose ps

      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .[milvus]

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "milvus and not integration" test/document_store_tests/ --document_store_type=milvus)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}


  weaviate-tests:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'weaviate')

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/
    
    - name: Setup Weaviate
      run: docker run -d -p 8080:8080 --name haystack_test_weaviate --env AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true' --env PERSISTENCE_DATA_PATH='/var/lib/weaviate' semitechnologies/weaviate:1.11.0

      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .[weaviate]

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "weaviate and not integration" test/document_store_tests/ --document_store_type=weaviate)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}


  pinecone-tests:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'pinecone')

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/
    
      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .[pinecone]

    - name: Run tests
      id: pytest
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "pinecone and not integration" test/document_store_tests/ --document_store_type=pinecone)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}


  graphdb-tests:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'graphdb')

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Setup GraphDB
      if: ${{ matrix.marker }} == "graphdb"
      run: docker run -d -p 7200:7200 --name haystack_test_graphdb deepset/graphdb-free:9.4.1-adoptopenjdk11
    
      # TODO Let's try to remove this one from the unit tests
    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install Haystack
      run: pip install .[graphdb]

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "graphdb and not integration" test/document_store_tests/ --document_store_type=graphdb)
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.tests_run }}


  rest-and-ui-tests:
    needs: unit-tests
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'api')
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Run Elasticsearch
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2

    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install REST API and UI
      run: |
        pip install rest_api/
        pip install ui/

    - name: Run tests
      id: pytest
      run: |
        export pytest_output=$(pytest rest_api/ ui/)
        echo $pytest_output
        
        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=rest_tests_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: ${{ steps.pytest.outputs.rest_tests_run }}


  integration-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false  # Avoid cancelling the others if one of these fails
      matrix: 
        folder:
          - "node_tests"
          - "pipeline_tests"
          - "modeling_tests"
          - "other_tests"
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Run Elasticsearch
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2

    - name: Run Milvus
      run: |
        cd ../../   # Avoid causing permission issues on hashFiles later by creating unreadable folders like "volumes"
        wget https://github.com/milvus-io/milvus/releases/download/v2.0.0/milvus-standalone-docker-compose.yml -O docker-compose.yml
        sudo docker-compose up -d
        sudo docker-compose ps

    - name: Run Weaviate
      run: docker run -d -p 8080:8080 --name haystack_test_weaviate --env AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true' --env PERSISTENCE_DATA_PATH='/var/lib/weaviate' semitechnologies/weaviate:1.11.0

    - name: Run GraphDB
      run: docker run -d -p 7200:7200 --name haystack_test_graphdb deepset/graphdb-free:9.4.1-adoptopenjdk11

    - name: Run Apache Tika
      run: docker run -d -p 9998:9998 -e "TIKA_CHILD_JAVA_OPTS=-JXms128m" -e "TIKA_CHILD_JAVA_OPTS=-JXmx128m" apache/tika:1.24.1

    - name: Run Parsr
      run: docker run -d -p 3001:3001 axarev/parsr:v1.2.2

    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz && tar -xvf xpdf-tools-linux-4.04.tar.gz && sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin

    - name: Install tesseract
      run: |
        sudo apt update
        sudo apt-get install tesseract-ocr libtesseract-dev poppler-utils

    - name: Install Haystack
      run: pip install .

    - name: Run tests
      id: pytest
      env:
        TOKENIZERS_PARALLELISM: 'false'  # Avoid logspam by tokenizers
      run: |
        export pytest_output=$(pytest -s --maxfail=5 --durations=10 -m "integration" test/${{ matrix.folder }})
        echo $pytest_output

        # Output successful tests
        [[ $pytest_output =~ (([0-9]+) passed) ]]
        echo "::set-output name=${{ matrix.folder }}_run::${BASH_REMATCH::-7}"
      
    outputs:
      tests-run: |
        ${{ steps.pytest.outputs.node_tests_run }} +
        ${{ steps.pytest.outputs.pipelines_tests_run }} +
        ${{ steps.pytest.outputs.modeling_tests_run }} +
        ${{ steps.pytest.outputs.other_tests_run }}


  count:
    needs: 
     - unit-tests
     - elasticsearch-tests
     - faiss-tests
     - milvus-tests
     - weaviate-tests
     - pinecone-tests
     - graphdb-tests
     - rest-and-ui-tests
     - integration-tests
    if: always()
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: ./.github/actions/linux_cache/

    - name: Count tests
      run: |
        # Count available tests
        [[ $(pytest --collect-only .) =~ (([0-9]+) tests collected) ]]
        export total_tests_count=${BASH_REMATCH::-6}

        export tests_run=${{ needs.unit-tests.outputs.tests-run }}
        export tests_run=$(( ${{ needs.rest-and-ui-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.integration-tests.outputs.tests-run }} + tests_run ))
        
        export tests_run=$(( ${{ needs.elasticsearch-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.faiss-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.milvus-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.weaviate-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.pinecone-tests.outputs.tests-run }} + tests_run ))
        export tests_run=$(( ${{ needs.graphdb-tests.outputs.tests-run }} + tests_run ))        
        
        echo "============ Tests run: $tests_run / $total_tests_count =============="
